"""Generate a cross-family replication table from per-model selectivity runs.

Reads each ``results/selectivity_h200_powered_<model>`` metrics.json and emits
both Markdown and LaTeX. The LaTeX file is the target of the
``\\maybeinputtable{../generated/active_primary/family_replication_table.tex}``
slot in the main manuscript.

Run: ``uv run python scripts/make_family_replication_table.py``
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

POLICY_ORDER = [
    "sliding_window__budget128",
    "sink_recent__budget128__sink8",
    "policy_pinned__budget128__sink8",
    "user_pinned__budget128__sink8",
    "random_matched__budget128__seed991",
]
POLICY_LABELS = {
    "sliding_window__budget128": "sliding window",
    "sink_recent__budget128__sink8": "sink+recent",
    "policy_pinned__budget128__sink8": "policy-pinned",
    "user_pinned__budget128__sink8": "user-pinned",
    "random_matched__budget128__seed991": "random matched",
}
MODEL_LABELS = {
    "qwen2_5_7b_base": "Qwen2.5-7B base",
    "qwen2_5_7b_instruct": "Qwen2.5-7B-Instruct",
    "qwen3_5_9b": "Qwen3-9B",
    "gpt_oss_20b": "GPT-OSS-20B",
    "llama3_1_8b_instruct": "Llama-3.1-8B-Instruct",
    "gemma2_9b_it": "Gemma-2-9B-IT",
    "mistral_7b_instruct_v0_3": "Mistral-7B-Instruct-v0.3",
    "olmo3_7b_instruct": "OLMo-3-7B-Instruct",
    "phi4": "Phi-4",
    "qwen2_5_14b_msm_rules": "Qwen2.5-14B-Instruct + MSM",
}
MODEL_FAMILIES = {
    "qwen2_5_7b_base": "Qwen",
    "qwen2_5_7b_instruct": "Qwen",
    "qwen3_5_9b": "Qwen",
    "gpt_oss_20b": "OpenAI",
    "llama3_1_8b_instruct": "Llama",
    "gemma2_9b_it": "Gemma",
    "mistral_7b_instruct_v0_3": "Mistral",
    "olmo3_7b_instruct": "OLMo",
    "phi4": "Phi",
    "qwen2_5_14b_msm_rules": "Qwen",
}


def collect_rows(results_root: Path) -> list[dict]:
    rows: list[dict] = []
    for run_dir in sorted(results_root.glob("selectivity_h200_powered_*")):
        if run_dir.name == "selectivity_h200_powered_combined":
            continue
        metrics_path = run_dir / "metrics.json"
        if not metrics_path.exists():
            continue
        model_key = run_dir.name.removeprefix("selectivity_h200_powered_")
        try:
            metrics = json.loads(metrics_path.read_text())
        except Exception:
            continue
        contrasts = metrics.get("policy_level_contrasts") or {}
        if not contrasts:
            continue
        policy_level = {}
        for policy_name, payload in contrasts.items():
            ssei = payload.get("selective_safety_erasure_index")
            ci = payload.get("selective_safety_erasure_index_ci") or {}
            policy_level[policy_name] = {
                "ssei": ssei,
                "ci_low": ci.get("ci_low"),
                "ci_high": ci.get("ci_high"),
            }
        rows.append(
            {
                "model_key": model_key,
                "model_label": MODEL_LABELS.get(model_key, model_key),
                "family": MODEL_FAMILIES.get(model_key, model_key),
                "policy_level": policy_level,
            }
        )
    return rows


def fmt(value, digits=3) -> str:
    if value is None:
        return "--"
    try:
        return f"{float(value):.{digits}f}"
    except (TypeError, ValueError):
        return "--"


def render_markdown(rows: list[dict]) -> str:
    policies = [p for p in POLICY_ORDER]
    header = "| Family | Model | " + " | ".join(POLICY_LABELS[p] + " SSEI [CI]" for p in policies) + " |"
    sep = "| --- | --- | " + " | ".join(["---"] * len(policies)) + " |"
    out = [header, sep]
    for r in rows:
        cells = [r["family"], r["model_label"]]
        for p in policies:
            entry = r["policy_level"].get(p) or {}
            ssei = entry.get("ssei")
            lo = entry.get("ci_low")
            hi = entry.get("ci_high")
            if ssei is None:
                cells.append("--")
            else:
                cells.append(f"{fmt(ssei)} [{fmt(lo)}, {fmt(hi)}]")
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out) + "\n"


def render_latex(rows: list[dict]) -> str:
    policies = [p for p in POLICY_ORDER]
    col_spec = "ll" + "r" * len(policies)
    def _escape(text: str) -> str:
        return text.replace("_", "\\_")

    header_cells = ["\\textbf{Family}", "\\textbf{Model}"] + [
        "\\textbf{" + _escape(POLICY_LABELS[p]) + "}" for p in policies
    ]
    lines = [
        "% Auto-generated by scripts/make_family_replication_table.py",
        "\\begin{table}[ht]",
        "\\centering",
        "\\caption{Cross-family selectivity (SSEI) by cache policy. SSEI is safety degradation minus capability degradation relative to the no-cache-policy baseline; positive SSEI indicates safety loss exceeding capability loss. 95\\% bootstrap CIs in brackets.}",
        "\\label{tab:family-replication}",
        "\\resizebox{\\textwidth}{!}{",
        f"\\begin{{tabular}}{{{col_spec}}}",
        "\\toprule",
        " & ".join(header_cells) + " \\\\",
        "\\midrule",
    ]
    for r in rows:
        cells = [r["family"], r["model_label"].replace("-", "--")]
        for p in policies:
            entry = r["policy_level"].get(p) or {}
            ssei = entry.get("ssei")
            lo = entry.get("ci_low")
            hi = entry.get("ci_high")
            if ssei is None:
                cells.append("--")
            else:
                cells.append(f"${fmt(ssei)}$ [{fmt(lo)}, {fmt(hi)}]")
        lines.append(" & ".join(cells) + " \\\\")
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "}",
        "\\end{table}",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results-root", type=Path, default=Path("results"))
    parser.add_argument("--output-dir", type=Path, default=Path("docs/generated/active_primary"))
    args = parser.parse_args()

    rows = collect_rows(args.results_root)
    if not rows:
        raise SystemExit("No selectivity panel runs with policy_level_ssei found.")
    args.output_dir.mkdir(parents=True, exist_ok=True)
    md_path = args.output_dir / "family_replication_table.md"
    tex_path = args.output_dir / "family_replication_table.tex"
    md_path.write_text(render_markdown(rows))
    tex_path.write_text(render_latex(rows))
    print(f"Wrote {md_path} and {tex_path} ({len(rows)} models).")


if __name__ == "__main__":
    main()
