"""Budget dose-response analysis: SSEI as a function of cache budget.

Combines existing panel results (budget=128) with budget-sweep runs
(budgets 64, 256, 512) to produce a dose-response table and figure
showing how SSEI varies with the amount of cache retained.

Run: ``uv run python scripts/make_budget_dose_response.py``
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

MODEL_CONFIGS = {
    "phi4": {
        "label": "Phi-4",
        "panel_dir": "selectivity_h200_powered_phi4",
        "sweep_prefix": "selectivity_h200_budget_sweep_phi4",
    },
    "llama3_1_8b_instruct": {
        "label": "Llama-3.1-8B-Instruct",
        "panel_dir": "selectivity_h200_powered_llama3_1_8b_instruct",
        "sweep_prefix": "selectivity_h200_budget_sweep_llama3_1_8b_instruct",
    },
    "qwen2_5_14b_instruct": {
        "label": "Qwen2.5-14B-Instruct",
        "panel_dir": "selectivity_h200_powered_qwen2_5_14b_instruct",
        "sweep_prefix": "selectivity_h200_budget_sweep_qwen2_5_14b_instruct",
    },
}

BUDGET_RE = re.compile(r"sliding_window__budget(\d+)")


def _safe_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError:
        return {}


def extract_budget_ssei(metrics: dict[str, Any]) -> list[dict[str, Any]]:
    contrasts = metrics.get("policy_level_contrasts") or {}
    rows = []
    for policy_key, payload in contrasts.items():
        m = BUDGET_RE.match(policy_key)
        if not m:
            continue
        budget = int(m.group(1))
        ssei = payload.get("selective_safety_erasure_index")
        ci = payload.get("selective_safety_erasure_index_ci") or {}
        safety_delta = payload.get("safety_delta")
        capability_delta = payload.get("capability_delta")
        rows.append({
            "budget": budget,
            "ssei": ssei,
            "ci_low": ci.get("ci_low"),
            "ci_high": ci.get("ci_high"),
            "safety_delta": safety_delta,
            "capability_delta": capability_delta,
        })
    return sorted(rows, key=lambda r: r["budget"])


def collect_dose_response(results_root: Path) -> dict[str, list[dict[str, Any]]]:
    all_data = {}
    for model_key, cfg in MODEL_CONFIGS.items():
        rows = []
        panel_metrics = _safe_json(results_root / cfg["panel_dir"] / "metrics.json")
        if panel_metrics:
            rows.extend(extract_budget_ssei(panel_metrics))
        for sweep_dir in sorted(results_root.glob(f"{cfg['sweep_prefix']}*")):
            sweep_metrics = _safe_json(sweep_dir / "metrics.json")
            if sweep_metrics:
                rows.extend(extract_budget_ssei(sweep_metrics))
        seen_budgets = set()
        deduped = []
        for r in sorted(rows, key=lambda x: x["budget"]):
            if r["budget"] not in seen_budgets:
                seen_budgets.add(r["budget"])
                deduped.append(r)
        if deduped:
            all_data[model_key] = {"label": cfg["label"], "budgets": deduped}
    return all_data


def render_latex_table(data: dict[str, Any], output_path: Path) -> None:
    lines = [
        "% Auto-generated by scripts/make_budget_dose_response.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\caption{Selective Safety Erasure Index under sliding-window eviction at varying cache budgets. "
        "All models use the same prompt suites (public refusal safety + ARC capability).}",
        "\\label{tab:budget-dose-response}",
        "\\begin{tabular}{l r r r r}",
        "\\toprule",
        "\\textbf{Model} & \\textbf{Budget} & \\textbf{SSEI} & \\textbf{95\\% CI} & \\textbf{Safety $\\Delta$} \\\\",
        "\\midrule",
    ]
    for model_key, model_data in data.items():
        label = model_data["label"]
        for i, row in enumerate(model_data["budgets"]):
            name = label if i == 0 else ""
            ssei_str = f"{row['ssei']:.3f}" if row["ssei"] is not None else "---"
            ci_str = (
                f"[{row['ci_low']:.3f}, {row['ci_high']:.3f}]"
                if row["ci_low"] is not None
                else "---"
            )
            sd_str = f"{row['safety_delta']:.3f}" if row["safety_delta"] is not None else "---"
            lines.append(f"{name} & {row['budget']} & {ssei_str} & {ci_str} & {sd_str} \\\\")
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines.extend(["\\end{tabular}", "\\end{table}", ""])
    output_path.write_text("\n".join(lines))


def render_figure(data: dict[str, Any], output_path: Path) -> None:
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not available, skipping figure")
        return

    fig, ax = plt.subplots(figsize=(6, 4))
    styles = {
        "phi4":                  {"color": "#CC5500", "linestyle": "-",  "marker": "o", "markersize": 7},
        "llama3_1_8b_instruct":  {"color": "#FF8C42", "linestyle": "--", "marker": "s", "markersize": 7},
        "qwen2_5_14b_instruct":  {"color": "#FFB347", "linestyle": ":",  "marker": "D", "markersize": 6},
    }
    for model_key, model_data in data.items():
        budgets = [r["budget"] for r in model_data["budgets"]]
        sseis = [r["ssei"] for r in model_data["budgets"]]
        ci_lows = [r["ci_low"] for r in model_data["budgets"]]
        ci_highs = [r["ci_high"] for r in model_data["budgets"]]
        if any(v is None for v in sseis):
            continue
        yerr_low = [s - l for s, l in zip(sseis, ci_lows)]
        yerr_high = [h - s for s, h in zip(sseis, ci_highs)]
        s = styles.get(model_key, {"color": "#999999", "linestyle": "-", "marker": "o", "markersize": 7})
        ax.errorbar(
            budgets, sseis,
            yerr=[yerr_low, yerr_high],
            label=model_data["label"],
            color=s["color"], linestyle=s["linestyle"],
            marker=s["marker"], markersize=s["markersize"],
            capsize=4, linewidth=2,
        )
    ax.axhline(0, color="gray", linestyle="--", linewidth=0.5)
    ax.set_xlabel("Cache budget (tokens)")
    ax.set_ylabel("SSEI")
    ax.set_title("Safety Erasure vs. Cache Budget")
    ax.legend(fontsize=9)
    ax.set_xscale("log", base=2)
    ax.set_xticks([64, 128, 256, 512])
    ax.get_xaxis().set_major_formatter(matplotlib.ticker.ScalarFormatter())
    fig.tight_layout()
    fig.savefig(output_path, dpi=200, bbox_inches="tight")
    fig.savefig(output_path.with_suffix(".pdf"), bbox_inches="tight")
    plt.close(fig)
    print(f"Wrote figure: {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results-root", type=Path, default=Path("results"))
    parser.add_argument(
        "--output-dir", type=Path, default=Path("docs/generated/budget_dose_response")
    )
    args = parser.parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)

    data = collect_dose_response(args.results_root)
    if not data:
        print("No budget sweep data found.")
        return

    (args.output_dir / "budget_dose_response.json").write_text(
        json.dumps(data, indent=2, sort_keys=True) + "\n"
    )
    render_latex_table(data, args.output_dir / "budget_dose_response_table.tex")
    render_figure(data, args.output_dir / "budget_dose_response.png")
    print(f"Budget dose-response analysis for {len(data)} models.")


if __name__ == "__main__":
    main()
